apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  namespace: api-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: kd-api
          image: k8-docker-api:latest
          ports:
            - containerPort: 3000