version: '3'
services:
  mysql-container:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"

  node-app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mysql-container