apiVersion: v1
kind: Service
metadata:
  name: mysql-container
  namespace: api-k8s
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 8045
      targetPort: 3000
  type: ClusterIP
